---
baseurl: "http://www.changingwealth.com/"
title: "Changing Wealth"
languageCode: "en-us"
metaDataFormat: "yaml"
theme: "changingwealth"
builddrafts: false
taxonomies:
  topic: "topics"
  issue: "issues"
  author: "authors"
  tag: "tags"
  language: "languages"
  publisher: "publishers"
  type: "types"
  
...
